# Generated by Django 5.2.4 on 2025-07-31 03:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire_base', models.FloatField()),
                ('primes_conges', models.FloatField()),
                ('indemnite_exoneree', models.FloatField()),
                ('nb_charge_familiale', models.IntegerField()),
                ('salaire_brut', models.FloatField()),
                ('salaire_brut_imposable', models.FloatField()),
                ('cnss', models.FloatField()),
                ('amo', models.FloatField()),
                ('mutuelle', models.FloatField()),
                ('frais_professionnels', models.FloatField()),
                ('salaire_net_imposable', models.FloatField()),
                ('ir_brut', models.FloatField()),
                ('charge_famille', models.FloatField()),
                ('ir_net', models.FloatField()),
                ('salaire_net', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
